import fs from 'fs';
import path from 'path';
import { SELECTORS } from '../constants.js';
import { capitalize, camelToKebab, escapeStringForCodeGen, sanitizeJsIdentifier, escapeJsDocComment, writeFileAtomic } from './utils.js';
import type { GeneratedPageObject, GeneratorOptions, ElementInfo } from '../types.js';

/**
 * Modal element info for generator (subset of ElementInfo, more flexible)
 */
interface ModalElementInfo {
  name: string;
  component: string;
  selector: string;
  action: string;
  description: string;
}

/**
 * Modal data structure accepted by generator
 * Flexible to accept both simple modal info and full analysis
 */
interface ModalData {
  modalName?: string;
  triggerElement?: string;
  purpose?: string;
  expectedContent?: string;
  elements?: ModalElementInfo[];
  actions?: {
    confirm?: string;
    cancel?: string;
  };
}

/**
 * Page data structure for generating Page Objects
 */
export interface PageData {
  pageAnalysis: {
    url: string;
    purpose: string;
    suggestedClassName?: string;
  };
  elements: ElementInfo[];
  modals: ModalData[];
}

/**
 * Generate Page Object code from analyzed page data
 * SECURITY: suggestedClassName from AI is sanitized to prevent code injection
 */
export function generatePageObject(pageData: PageData, options: GeneratorOptions = {}): GeneratedPageObject {
  const { typescript = false } = options;
  const ext = typescript ? 'ts' : 'js';

  // CRITICAL: Sanitize AI-provided className to prevent code injection
  const rawClassName = pageData.pageAnalysis.suggestedClassName || pathToClassName(pageData.pageAnalysis.url);
  const className = sanitizeClassName(rawClassName);

  const code = buildPageObjectCode(pageData, className, typescript);

  return { code, className, ext };
}

/**
 * Sanitize class name to be a valid JavaScript/TypeScript class identifier
 * Prevents code injection via malicious AI responses
 */
function sanitizeClassName(name: string): string {
  if (!name) return 'UnnamedPage';

  // Remove any non-alphanumeric characters except underscore
  let sanitized = name.replace(/[^a-zA-Z0-9_]/g, '');

  // Ensure starts with uppercase letter (PascalCase for classes)
  if (!sanitized || !/^[A-Z]/.test(sanitized)) {
    sanitized = 'Page' + capitalize(sanitized || 'Unknown');
  }

  // Ensure ends with 'Page' for consistency
  if (!sanitized.endsWith('Page')) {
    sanitized += 'Page';
  }

  return sanitized;
}

function buildPageObjectCode(pageData: PageData, className: string, typescript: boolean): string {
  const parts: string[] = [];

  parts.push(generateImports(typescript));
  parts.push(generateClassHeader(pageData, className));
  parts.push(generateTypeDeclarations(typescript));
  parts.push(generateConstructor(pageData, typescript));
  parts.push(generateMethods(pageData));
  parts.push('}\n');

  return parts.join('');
}

function generateImports(typescript: boolean): string {
  if (typescript) {
    return `import { Page, Locator } from '@playwright/test';\n\n`;
  }
  return '';
}

function generateClassHeader(pageData: PageData, className: string): string {
  return `/**
 * Page Object for ${escapeJsDocComment(pageData.pageAnalysis.url)}
 * ${escapeJsDocComment(pageData.pageAnalysis.purpose)}
 *
 * @generated Automatically generated by po-generator
 */
export class ${className} {
`;
}

function generateTypeDeclarations(typescript: boolean): string {
  if (typescript) {
    return `  page: Page;\n  url: string;\n\n`;
  }
  return '';
}

function generateConstructor(pageData: PageData, typescript: boolean): string {
  const typeAnnotation = typescript ? ': Page' : '';
  const pageType = typescript ? 'Page' : 'import("@playwright/test").Page';

  // Escape URL to prevent code injection via malicious URL parameters
  const escapedUrl = escapeStringForCodeGen(pageData.pageAnalysis.url);

  let code = `  /**
   * @param {${pageType}} page
   */
  constructor(page${typeAnnotation}) {
    this.page = page;
    this.url = '${escapedUrl}';\n\n`;

  code += generateElementDeclarations(pageData.elements);
  code += generateModalDeclarations(pageData.modals);
  code += `  }\n\n`;

  return code;
}

/**
 * Sanitize element name for safe use in generated code
 * Defense-in-depth: even though schema validates, we sanitize at point of use
 */
function safeElementName(name: string): string {
  return sanitizeJsIdentifier(name);
}

function generateElementDeclarations(elements: ElementInfo[]): string {
  if (!elements || elements.length === 0) return '';

  // Use array accumulation instead of string += for performance
  const lines: string[] = ['    // Elements'];
  for (const el of elements) {
    const safeName = safeElementName(el.name);
    lines.push(`    /** ${escapeJsDocComment(el.description)} */`);
    lines.push(`    this.${safeName} = page.locator('${escapeStringForCodeGen(el.selector)}');`);
    lines.push('');
  }
  return lines.join('\n');
}

// Pre-compute modal content selectors for performance
const MODAL_CONTENT_PARTS = SELECTORS.MODAL_CONTENT.split(', ');

function generateModalDeclarations(modals: ModalData[]): string {
  if (!modals || modals.length === 0) return '';

  // Use array accumulation instead of string += for performance
  const lines: string[] = [];

  for (const modal of modals) {
    if (modal.elements && modal.elements.length > 0) {
      // Sanitize modal name to prevent code injection
      const rawModalName = modal.modalName || modal.triggerElement || 'modal';
      const modalName = sanitizeJsIdentifier(rawModalName);
      lines.push(`    // Modal: ${modalName}`);
      lines.push(`    this.${modalName} = {`);
      lines.push(`      container: page.locator('${SELECTORS.MODAL}'),`);

      for (const el of modal.elements) {
        const safeName = safeElementName(el.name);
        const selector = escapeStringForCodeGen(el.selector);
        lines.push(`      /** ${escapeJsDocComment(el.description)} */`);
        // Use pre-computed MODAL_CONTENT_PARTS for performance
        const fullSelector = MODAL_CONTENT_PARTS.map(m => `${m} ${selector}`).join(', ');
        lines.push(`      ${safeName}: page.locator('${fullSelector}'),`);
      }

      if (modal.actions) {
        if (modal.actions.confirm) {
          lines.push(`      confirm: page.locator('${escapeStringForCodeGen(modal.actions.confirm)}'),`);
        }
        if (modal.actions.cancel) {
          lines.push(`      cancel: page.locator('${escapeStringForCodeGen(modal.actions.cancel)}'),`);
        }
      }

      lines.push('    };');
      lines.push('');
    }
  }

  return lines.join('\n');
}

function generateMethods(pageData: PageData): string {
  const parts: string[] = [];

  parts.push(generateNavigationMethods());
  parts.push(generateFillMethods(pageData.elements));
  parts.push(generateSelectMethods(pageData.elements));
  parts.push(generateClickMethods(pageData.elements));
  parts.push(generateModalMethods(pageData.modals));

  return parts.join('');
}

function generateNavigationMethods(): string {
  return `  /**
   * Navigate to page
   */
  async goto() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Wait for page to load
   */
  async waitForLoad() {
    await this.page.waitForSelector('body');
  }

`;
}

function generateFillMethods(elements: ElementInfo[]): string {
  if (!elements) return '';

  const fillElements = elements.filter((e) => e.action === 'fill');
  if (fillElements.length === 0) return '';

  // Use array accumulation for performance
  const methods = fillElements.map((el) => {
    const safeName = safeElementName(el.name);
    return `  /**
   * Fill ${escapeJsDocComment(el.description)}
   * @param {string} value
   */
  async fill${capitalize(safeName)}(value: string) {
    await this.${safeName}.locator('input, textarea').fill(value);
  }`;
  });

  return methods.join('\n\n') + '\n\n';
}

function generateSelectMethods(elements: ElementInfo[]): string {
  if (!elements) return '';

  const selectElements = elements.filter((e) => e.action === 'select');
  if (selectElements.length === 0) return '';

  // Use array accumulation for performance
  const methods = selectElements.map((el) => {
    const safeName = safeElementName(el.name);
    return `  /**
   * Select value in ${escapeJsDocComment(el.description)}
   * @param {string} option
   */
  async select${capitalize(safeName)}(option: string) {
    await this.${safeName}.locator('${SELECTORS.FIELD_TRIGGER}').click();
    await this.page.locator('${SELECTORS.DROPDOWN_ITEM}').filter({ hasText: option }).click();
  }`;
  });

  return methods.join('\n\n') + '\n\n';
}

function generateClickMethods(elements: ElementInfo[]): string {
  if (!elements) return '';

  const clickElements = elements.filter((e) => e.action === 'click' && e.importance === 'high');
  if (clickElements.length === 0) return '';

  // Use array accumulation for performance
  const methods = clickElements.map((el) => {
    const safeName = safeElementName(el.name);
    return `  /**
   * Click ${escapeJsDocComment(el.description)}
   */
  async click${capitalize(safeName)}() {
    await this.${safeName}.click();
  }`;
  });

  return methods.join('\n\n') + '\n\n';
}

function generateModalMethods(modals: ModalData[]): string {
  if (!modals) return '';

  let code = '';

  for (const modal of modals) {
    if (modal.modalName) {
      // Sanitize modal name to prevent code injection
      const modalName = sanitizeJsIdentifier(modal.modalName);
      code += `  /**
   * Open modal ${modalName}
   */
  async open${capitalize(modalName)}() {
    await this.${modalName}.container.waitFor();
  }

  /**
   * Close modal ${modalName}
   */
  async close${capitalize(modalName)}() {
    await this.page.keyboard.press('Escape');
    await this.${modalName}.container.waitFor({ state: 'hidden' });
  }

`;
    }
  }

  return code;
}

/**
 * Save Page Object code to file (atomic write)
 */
export function savePageObject(pageObjectCode: string, className: string, outputDir: string, ext = 'js'): string {
  const fileName = `${camelToKebab(className)}.${ext}`;
  const filePath = path.join(outputDir, fileName);

  fs.mkdirSync(outputDir, { recursive: true });
  writeFileAtomic(filePath, pageObjectCode);

  return filePath;
}

/**
 * Generate index file that exports all Page Objects (atomic write)
 */
export function generateIndexFile(classNames: string[], outputDir: string, ext = 'js'): string {
  let code = '// Auto-generated index file\n\n';

  for (const className of classNames) {
    // Sanitize at point of use — defense-in-depth for public API
    const safeName = sanitizeJsIdentifier(className);
    const fileName = camelToKebab(safeName);
    code += `export { ${safeName} } from './${fileName}.${ext}';\n`;
  }

  const filePath = path.join(outputDir, `index.${ext}`);
  writeFileAtomic(filePath, code);

  return filePath;
}

// Helper functions

/**
 * Convert URL path to PascalCase class name
 * @param urlPath - URL path (e.g., '/users/settings')
 * @returns PascalCase class name with 'Page' suffix (e.g., 'UsersSettingsPage')
 * @example
 *   pathToClassName('/') => 'HomePage'
 *   pathToClassName('/dashboard') => 'DashboardPage'
 *   pathToClassName('/users/profile') => 'UsersProfilePage'
 */
function pathToClassName(urlPath: string): string {
  if (!urlPath || urlPath === '/') return 'HomePage';

  return (
    urlPath
      .split('/')
      .filter(Boolean)
      .map(capitalize)
      .join('') + 'Page'
  );
}
