import fs from 'fs';
import path from 'path';
import { SELECTORS } from '../constants.js';
import { capitalize, camelToKebab, escapeSelector, sanitizeJsIdentifier } from './utils.js';
import type { GeneratedPageObject, GeneratorOptions, ElementInfo } from '../types.js';

/**
 * Modal element info for generator (subset of ElementInfo, more flexible)
 */
interface ModalElementInfo {
  name: string;
  component: string;
  selector: string;
  action: string;
  description: string;
}

/**
 * Modal data structure accepted by generator
 * Flexible to accept both simple modal info and full analysis
 */
interface ModalData {
  modalName?: string;
  triggerElement?: string;
  purpose?: string;
  expectedContent?: string;
  elements?: ModalElementInfo[];
  actions?: {
    confirm?: string;
    cancel?: string;
  };
}

/**
 * Page data structure for generating Page Objects
 */
export interface PageData {
  pageAnalysis: {
    url: string;
    purpose: string;
    suggestedClassName?: string;
  };
  elements: ElementInfo[];
  modals: ModalData[];
}

/**
 * Generate Page Object code from analyzed page data
 */
export function generatePageObject(pageData: PageData, options: GeneratorOptions = {}): GeneratedPageObject {
  const { typescript = false } = options;
  const ext = typescript ? 'ts' : 'js';
  const className = pageData.pageAnalysis.suggestedClassName || pathToClassName(pageData.pageAnalysis.url);

  const code = buildPageObjectCode(pageData, className, typescript);

  return { code, className, ext };
}

function buildPageObjectCode(pageData: PageData, className: string, typescript: boolean): string {
  const parts: string[] = [];

  parts.push(generateImports(typescript));
  parts.push(generateClassHeader(pageData, className));
  parts.push(generateTypeDeclarations(typescript));
  parts.push(generateConstructor(pageData, typescript));
  parts.push(generateMethods(pageData));
  parts.push('}\n');

  return parts.join('');
}

function generateImports(typescript: boolean): string {
  if (typescript) {
    return `import { Page, Locator } from '@playwright/test';\n\n`;
  }
  return '';
}

function generateClassHeader(pageData: PageData, className: string): string {
  return `/**
 * Page Object for ${pageData.pageAnalysis.url}
 * ${pageData.pageAnalysis.purpose}
 *
 * @generated Automatically generated by po-generator
 */
export class ${className} {
`;
}

function generateTypeDeclarations(typescript: boolean): string {
  if (typescript) {
    return `  page: Page;\n  url: string;\n\n`;
  }
  return '';
}

function generateConstructor(pageData: PageData, typescript: boolean): string {
  const typeAnnotation = typescript ? ': Page' : '';
  const pageType = typescript ? 'Page' : 'import("@playwright/test").Page';

  // Escape URL to prevent code injection via malicious URL parameters
  const escapedUrl = pageData.pageAnalysis.url.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

  let code = `  /**
   * @param {${pageType}} page
   */
  constructor(page${typeAnnotation}) {
    this.page = page;
    this.url = '${escapedUrl}';\n\n`;

  code += generateElementDeclarations(pageData.elements);
  code += generateModalDeclarations(pageData.modals);
  code += `  }\n\n`;

  return code;
}

function generateElementDeclarations(elements: ElementInfo[]): string {
  if (!elements || elements.length === 0) return '';

  let code = `    // Elements\n`;
  for (const el of elements) {
    code += `    /** ${el.description} */\n`;
    code += `    this.${el.name} = page.locator('${escapeSelector(el.selector)}');\n\n`;
  }
  return code;
}

function generateModalDeclarations(modals: ModalData[]): string {
  if (!modals || modals.length === 0) return '';

  let code = '';
  for (const modal of modals) {
    if (modal.elements && modal.elements.length > 0) {
      // Sanitize modal name to prevent code injection
      const rawModalName = modal.modalName || modal.triggerElement || 'modal';
      const modalName = sanitizeJsIdentifier(rawModalName);
      code += `    // Modal: ${modalName}\n`;
      code += `    this.${modalName} = {\n`;
      code += `      container: page.locator('${SELECTORS.MODAL}'),\n`;

      for (const el of modal.elements) {
        const selector = escapeSelector(el.selector);
        code += `      /** ${el.description} */\n`;
        // Use MODAL_CONTENT selector pattern for framework compatibility
        code += `      ${el.name}: page.locator('${SELECTORS.MODAL_CONTENT.split(', ').map(m => `${m} ${selector}`).join(', ')}'),\n`;
      }

      if (modal.actions) {
        if (modal.actions.confirm) {
          code += `      confirm: page.locator('${escapeSelector(modal.actions.confirm)}'),\n`;
        }
        if (modal.actions.cancel) {
          code += `      cancel: page.locator('${escapeSelector(modal.actions.cancel)}'),\n`;
        }
      }

      code += `    };\n\n`;
    }
  }
  return code;
}

function generateMethods(pageData: PageData): string {
  const parts: string[] = [];

  parts.push(generateNavigationMethods());
  parts.push(generateFillMethods(pageData.elements));
  parts.push(generateSelectMethods(pageData.elements));
  parts.push(generateClickMethods(pageData.elements));
  parts.push(generateModalMethods(pageData.modals));

  return parts.join('');
}

function generateNavigationMethods(): string {
  return `  /**
   * Navigate to page
   */
  async goto() {
    await this.page.goto(this.url);
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Wait for page to load
   */
  async waitForLoad() {
    await this.page.waitForSelector('body');
  }

`;
}

function generateFillMethods(elements: ElementInfo[]): string {
  if (!elements) return '';

  const fillElements = elements.filter((e) => e.action === 'fill');
  let code = '';

  for (const el of fillElements) {
    code += `  /**
   * Fill ${el.description}
   * @param {string} value
   */
  async fill${capitalize(el.name)}(value: string) {
    await this.${el.name}.locator('input, textarea').fill(value);
  }

`;
  }

  return code;
}

function generateSelectMethods(elements: ElementInfo[]): string {
  if (!elements) return '';

  const selectElements = elements.filter((e) => e.action === 'select');
  let code = '';

  for (const el of selectElements) {
    code += `  /**
   * Select value in ${el.description}
   * @param {string} option
   */
  async select${capitalize(el.name)}(option: string) {
    await this.${el.name}.locator('${SELECTORS.FIELD_TRIGGER}').click();
    await this.page.locator('${SELECTORS.DROPDOWN_ITEM}').filter({ hasText: option }).click();
  }

`;
  }

  return code;
}

function generateClickMethods(elements: ElementInfo[]): string {
  if (!elements) return '';

  const clickElements = elements.filter((e) => e.action === 'click' && e.importance === 'high');
  let code = '';

  for (const el of clickElements) {
    code += `  /**
   * Click ${el.description}
   */
  async click${capitalize(el.name)}() {
    await this.${el.name}.click();
  }

`;
  }

  return code;
}

function generateModalMethods(modals: ModalData[]): string {
  if (!modals) return '';

  let code = '';

  for (const modal of modals) {
    if (modal.modalName) {
      // Sanitize modal name to prevent code injection
      const modalName = sanitizeJsIdentifier(modal.modalName);
      code += `  /**
   * Open modal ${modalName}
   */
  async open${capitalize(modalName)}() {
    await this.${modalName}.container.waitFor();
  }

  /**
   * Close modal ${modalName}
   */
  async close${capitalize(modalName)}() {
    await this.page.keyboard.press('Escape');
    await this.${modalName}.container.waitFor({ state: 'hidden' });
  }

`;
    }
  }

  return code;
}

/**
 * Save Page Object code to file
 */
export function savePageObject(pageObjectCode: string, className: string, outputDir: string, ext = 'js'): string {
  const fileName = `${camelToKebab(className)}.${ext}`;
  const filePath = path.join(outputDir, fileName);

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(filePath, pageObjectCode);

  return filePath;
}

/**
 * Generate index file that exports all Page Objects
 */
export function generateIndexFile(classNames: string[], outputDir: string, ext = 'js'): string {
  let code = '// Auto-generated index file\n\n';

  for (const className of classNames) {
    const fileName = camelToKebab(className);
    code += `export { ${className} } from './${fileName}.${ext}';\n`;
  }

  const filePath = path.join(outputDir, `index.${ext}`);
  fs.writeFileSync(filePath, code);

  return filePath;
}

// Helper functions

/**
 * Convert URL path to PascalCase class name
 * @param urlPath - URL path (e.g., '/users/settings')
 * @returns PascalCase class name with 'Page' suffix (e.g., 'UsersSettingsPage')
 * @example
 *   pathToClassName('/') => 'HomePage'
 *   pathToClassName('/dashboard') => 'DashboardPage'
 *   pathToClassName('/users/profile') => 'UsersProfilePage'
 */
function pathToClassName(urlPath: string): string {
  if (!urlPath || urlPath === '/') return 'HomePage';

  return (
    urlPath
      .split('/')
      .filter(Boolean)
      .map(capitalize)
      .join('') + 'Page'
  );
}
